apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sa-bank
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - sa-bank-app
